extern bool CascadeRunning;
extern double CubeHeight;
extern bool rotright;
extern bool interrupted;
extern double holdTarget;
extern int armGoing;
#define armAllIn = -20;
#define armAllOut = 1000;
#define armAllOutReleased = 1300;
extern double currentX;
extern double currentY;
extern double currentA;
extern bool StackerRunning;